### ISSUE TITLE
onChange handler button and checkbox 

### ISSUE THREAD

**Issue by virginiarcruz** [austinroy/multistep-form#1]
How do I get values of the buttons and checkbox?

**Comment by virginiarcruz** [comment]
I can save the value, but doesn’t works when I invoke in another component

**Comment by austinroy** [comment]
The `handleChange` function is in the `MainForm` higher order component, I passed it down to the other components as props and had it called on individual inputs. What exactly are you trying to do so I can help out?

**Comment by austinroy** [comment]
Also, I don't think I had a checkbox included on this one 😅

**Comment by virginiarcruz** [comment]
I added two buttons (yes and no) here.
https://codesandbox.io/s/r1lm9j22l4

I want to save the values to buttons when I click in salve the value (true = yes or false = no) on button.
I have checkbox too, then I need to save the values of checkbox too.

**Comment by austinroy** [comment]
Let me look into it and get back to you on it

**Comment by austinroy** [comment]
Hey, apologies for the delay, but this is a small fix I came up with for that https://github.com/austinroy/multistep-form/pull/2 

I believe a similar approach should apply for a checkbox, the issue might have been the difference in how they handle inputs differently

**Comment by virginiarcruz** [comment]
It's ok.
Thank you :)

I did a similar solution because I had 2 steps with toogleButtons.
Then did one `handleChange `for each.
For example:

```
handleChangeStep1 = (value) => {
        this.setState({  value  });
 }

handleChangeStep2 = (value ) => {
        this.setState({  value  });
 }

```

Inside of component:

```
onClick = (value) => {
        this.props.handleChange(value)
 }
```

and on the switch button:

```
<Button
    className={this.props.value ? style.active : style.default}
    onClick={ () => this.onClick(true) } >
    Yes
</Button>
<Button
    className={!this.props.value ? style.active : style.default}
    onClick={ () => this.onClick(false) }>
    No
</Button>
```
